import fs from 'node:fs';
import path from 'node:path';

const OUT = 'src/shared/design/tokens/shadcn-theme.css';

const light = {
  '--background': 'var(--w-100)',
  '--foreground': 'var(--text-pri)',

  '--card': 'var(--w-100)',
  '--card-foreground': 'var(--text-pri)',

  '--popover': 'var(--w-100)',
  '--popover-foreground': 'var(--text-pri)',

  '--primary': 'var(--runddy-blue)',
  '--primary-foreground': 'var(--w-100)',

  '--secondary': 'var(--g-10)',
  '--secondary-foreground': 'var(--text-sec)',

  '--muted': 'var(--g-10)',
  '--muted-foreground': 'var(--text-ter)',

  '--accent': 'var(--runddy-pink)',
  '--accent-foreground': 'var(--g-100)',

  '--destructive': 'var(--state-error)',
  '--destructive-foreground': 'var(--w-100)',

  '--border': 'var(--line-ter)',
  '--input': 'var(--g-20)',
  '--ring': 'var(--runddy-blue)',

  '--radius': '12px'
};

const toCss = (vars: Record<string, string>) =>
  Object.entries(vars)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n');

const css = `/* AUTO-GENERATED by scripts/tokens/generate-shadcn-theme.ts */
:root {
${toCss(light)}
}
`;

fs.writeFileSync(OUT, css);
console.log('✅ generated:', path.resolve(OUT));
