import fs from 'node:fs';
import path from 'node:path';

const SRC = 'src/shared/design/tokens/tokens.json';
const OUT = 'src/shared/design/tokens/tw-typography.ts';

type AnyObj = Record<string, any>;

const walk = (obj: AnyObj, pathArr: string[] = [], acc: AnyObj = {}) => {
  for (const key of Object.keys(obj)) {
    const node = obj[key];
    if (
      node &&
      typeof node === 'object' &&
      'type' in node &&
      node.type === 'typography'
    ) {
      const name = [...pathArr, key]
        .join('-')
        .replace(/\s+/g, '-')
        .toLowerCase();
      acc[name] = {
        fontSize: `var(--${name}-font-size)`,
        lineHeight: `var(--${name}-line-height)`,
        letterSpacing: `var(--${name}-letter-spacing)`,
        fontWeight: `var(--${name}-font-weight)`,
        fontFamily: `var(--${name}-font-family)`
      };
    } else if (node && typeof node === 'object') {
      walk(node, [...pathArr, key], acc);
    }
  }
  return acc;
};

const raw = JSON.parse(fs.readFileSync(SRC, 'utf8'));
const map = walk(raw);

const header = `/* AUTO-GENERATED by scripts/tokens/generate-typography.ts */
export type TwTypography = Record<string, [string, { lineHeight?: string; letterSpacing?: string; fontWeight?: string; fontFamily?: string }]>;`;

const bodyLines = Object.entries(map).map(([k, v]) => {
  return `  "${k}": ["${v.fontSize}", { lineHeight: "${v.lineHeight}", letterSpacing: "${v.letterSpacing}", fontWeight: "${v.fontWeight}", fontFamily: "${v.fontFamily}" }],`;
});

const file = `${header}
export const twTypography: TwTypography = {
${bodyLines.join('\n')}
};`;

fs.writeFileSync(OUT, file);
console.log('✅ generated:', path.resolve(OUT));
